// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: remote_cdm_session_data.proto

package remote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device            string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	DeviceSessionData []byte `protobuf:"bytes,2,opt,name=device_session_data,json=deviceSessionData,proto3" json:"device_session_data,omitempty"`
}

func (x *SessionData) Reset() {
	*x = SessionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_cdm_session_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionData) ProtoMessage() {}

func (x *SessionData) ProtoReflect() protoreflect.Message {
	mi := &file_remote_cdm_session_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionData.ProtoReflect.Descriptor instead.
func (*SessionData) Descriptor() ([]byte, []int) {
	return file_remote_cdm_session_data_proto_rawDescGZIP(), []int{0}
}

func (x *SessionData) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *SessionData) GetDeviceSessionData() []byte {
	if x != nil {
		return x.DeviceSessionData
	}
	return nil
}

var File_remote_cdm_session_data_proto protoreflect.FileDescriptor

var file_remote_cdm_session_data_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x63, 0x64, 0x6d, 0x5f, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x22, 0x55, 0x0a, 0x0b, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e,
	0x0a, 0x13, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x22,
	0x48, 0x03, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x2d, 0x77, 0x65, 0x62, 0x64, 0x6c, 0x2f, 0x64, 0x72, 0x6d, 0x2f, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_remote_cdm_session_data_proto_rawDescOnce sync.Once
	file_remote_cdm_session_data_proto_rawDescData = file_remote_cdm_session_data_proto_rawDesc
)

func file_remote_cdm_session_data_proto_rawDescGZIP() []byte {
	file_remote_cdm_session_data_proto_rawDescOnce.Do(func() {
		file_remote_cdm_session_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_remote_cdm_session_data_proto_rawDescData)
	})
	return file_remote_cdm_session_data_proto_rawDescData
}

var file_remote_cdm_session_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_remote_cdm_session_data_proto_goTypes = []interface{}{
	(*SessionData)(nil), // 0: remote.SessionData
}
var file_remote_cdm_session_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_remote_cdm_session_data_proto_init() }
func file_remote_cdm_session_data_proto_init() {
	if File_remote_cdm_session_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_remote_cdm_session_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_remote_cdm_session_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remote_cdm_session_data_proto_goTypes,
		DependencyIndexes: file_remote_cdm_session_data_proto_depIdxs,
		MessageInfos:      file_remote_cdm_session_data_proto_msgTypes,
	}.Build()
	File_remote_cdm_session_data_proto = out.File
	file_remote_cdm_session_data_proto_rawDesc = nil
	file_remote_cdm_session_data_proto_goTypes = nil
	file_remote_cdm_session_data_proto_depIdxs = nil
}
